### ISSUE TITLE
Question: Stacking stacknavigation with TabNavigation

### ISSUE THREAD

**Issue by puzpuz** [exponent/ex-navigation#426]
I'm a a completely new with expo here, and would like to ask a question
If I have screens with the following hierarchy:
-LoginScreen
-MainScreen(with tab navigation)
---Tab 1
---Tab 2
---Tab3

when first run the application I would like to show LoginScreen first, then after successfully authenticated, I will navigate to MainScreen with 3 tabs.

I cannot find any example for such implementation, can anybody point me out to some example or just give me some :) thanks in advance

**Comment by EricCarrGH** [comment]
What I do is reset the stack on successful login like ths:

```
 this.props.navigator.immediatelyResetStack([Router.getRoute('mainScreen')]);
```

That prevents the back button from returning the user to the login page. 

More complete example:

in my App.js:
```
<NavigationProvider router={Router}>
        <StackNavigation 
          initialRoute={Router.getRoute('login')} />
</NavigationProvider>
```

in my Login.js:
```
onSignIn = () => {    
      this.setState({submitting: true})             

       biz.loginAsync(this.state).then((result)=> {
          this.setState({submitting: false});
          this.props.navigator.immediatelyResetStack([Router.getRoute('mainScreen')]);
      });
  }
```

in my MainScreen.js:

```
<TabNavigation...>
```

**BIG NOTICE**
Ex-Navigation is no longer being actively worked on. I'd suggest looking here for navigation in a new project: https://github.com/react-community/react-navigation.  Otherwise, you may run into other issues/inconsistencies that the maintainer won't be willing to fix and you will have wasted a lot of time integrating a deprecated navigation library. Ex-Navigation basically wraps a bunch of code from other developers for each of the navigation types, and I find I have to dig in the code to find the original github projects/documentation, discover that the ex-navigation hides the option I need, and hack it myself if I want that option. Be prepared to "do it yourself" if you are on any sort of timeline.

**Comment by puzpuz** [comment]
Good point, and thanks a lot with the big notice. I was quite get use to RNRF before, but I want to explore other options for routing. I will look into react-navigation
